#!/bin/bash
. function.sh

init()
{

	echo a=$a
	a=14
	local a=15
	echo a=$a
	#caller 0
	echo "returning 1"
	#return 1

	return 1
}

function test1()
{
	echo $0 $* $SUDO_COMMAND
	i=1
	while [[ i -lt 10 ]]
	do
		echo "i=$i"
		(( i += 1 ))
	done

	exit

	while getopts ":mnopq:rs" o
	do
		case $o in
			m) echo "m [OPTIND=${OPTIND}]";;
			n|o) echo "$o [OPTIND=${OPTIND}]";;
			p) echo "p [OPTIND=${OPTIND}]";;
			q) echo "q argument \"$OPTARG\" [OPTIND=${OPTIND}]";;
			r|s) echo "$o [OPTIND=${OPTIND}]";;
			*) echo "usage: -mnoprs -q <file>";;
		esac

	done
	shift $(( $OPTIND - 1 ))

	source test2.sh this is cool
	echo returned $?
	echo "a=$a"

	test2()
	{
		for arg in "$@"
		do
			echo "[$arg]"
		done
	}

	test2 $@

		# echo "\$#=$#"
	# echo "\$1=$1"
	# echo "\$2=$2"
	# echo "\$@=\"$@\""
	# echo "\$*=\"$*\""

	ttySettings=`stty -g`
	stty -icanon
	echo -n "Are you cool? (y)? "
	key=$(dd bs=1 count=1 2> /dev/null)
	stty "$ttySettings"
	echo

	# echo "BASH_SUBSHELL=$BASH_SUBSHELL"

	# let a="12 + 12"
	# echo $E_BADARGS

	# (( $# != 2)) && \
		# echo "usage: `basename $0` source destination" && exit 1

	# (( $# != 2)) && echo true || echo false

	#if [[ "a" == "b" && `echo hi` == "hi" ]]
	# a=
	# b=this
	# if [ "$a" == "$b" ]
	# then echo true
	# else echo false
	# fi
}

init
echo result=$?
